### ISSUE TITLE
Custom error message in Fail

### ISSUE THREAD

**Issue by potan** [com-lihaoyi/fastparse#243]
Please add string parameter to Fail parser to produce custom error message.

**Comment by byF** [comment]
I've got the same need, @lihaoyi would you be interested in a PR? It seems pretty straightforward.

**Comment by lihaoyi** [comment]
Sure seems reasonable. Having both `Fail("msg")` and `Pass[T](value: T)` overloads seems like they would come in handy

**Comment by bwbecker** [comment]
Any progress on this?  I see it was also raised in issues #213 and #187 .  I wrote up my best solution to date on [StackOverflow](https://stackoverflow.com/questions/72207813/how-to-provide-an-explicit-error-failure-message-in-the-scala-fastparse-library?noredirect=1#comment127761206_72207813) with suggestions from #213, but it is still far from ideal.

I think, frankly, that augmenting the `Fail` parser is only a small step forward.  I think the `Fail` parser is aimed at errors discovered by the parser itself (ie the grammar is violated).  What's asked for in #213 and my motivation is handling an error discovered in the actions.  For example, parsing a string that should be a regular expression but throws an error when you try to construct the RE.  I think this situation needs a second format for the error message.  Instead of "Expected ..., found ..." something like "Error .... found while parsing ....".

Thanks for your efforts!  Love the library but have a use case that I think is common and not yet handled well.
